// Script to parse and generate first 200 words
const fs = require('fs');

const rawText = `1.copy 复印 2.clock 钟 3.letter 信，字母 4.ticket 票 5.transportation 交通 6.goals 目标 7.energy 能量
8.experience 经验 9.January 1 月 10.Second 第二 11.America 美国 12.Britain 英国 13.London 伦敦
14.England 英格兰 15.Scotland 苏格兰 16.Queensland 昆士兰 17.Sydney 悉尼 18.Adelaide 阿德莱德
19.Melbourne 墨尔本 20.Perth 珀斯 21.fire 火灾，解雇 22.college 学院 23.teams 小组 24.membership 会
员 资 格 25.difficulties 困 难 26.beach 海 滩 27.underground 地 下 28.spending 花 费 29.site 位 置
30.recreation 娱乐 31.property 财产 32.learn 学习 33.computers 电脑 34.plant 植物 35.table 桌子
36.support 支 持 37.choice 选 择 38.glass 玻 璃 39.survey 调 查 40.passport 护 照 41.range 范 围
42.service 服务 43.exams 考试 44.failure 失败 45.demonstration 示威 46.festival 节日 47.Belfast 贝尔
法斯特 48.Ireland 爱尔兰 49.Dublin 都柏林 50.Australia 澳大利亚 51.narrator 叙述者 52.costs 成本
53.background 背景 54.Avenue 大街 55.senior 高级的，大四学生 56.deposit 押金 57.extra 额外的
58.tape 磁带 59.title 标题 60.culture 文化 61.dark 黑暗的 62.regular 规律的幼儿园 63.project 项目
64.December 12 月 65.November 11 月 66.beginning 开 始 67.purpose 目 的 68.interest 兴 趣
69.decoration 装修，装饰70.migration 迁徙，移民71.party 晚会72.relationship 关系73.environmental
环境 的 74.disease 疾病 75.Monday 周一 76.Wednesday 周三 77.century 世纪 78.equipment 设 备
79.methods 方法 80.location 地理位置 81.transport 交通 82.campus 校园 83.ideas 观点 84.world 世界
85.coffee 咖啡 86.Third 第三 87.Fourth 第四 88.cause 起因 89.social 社会的 90.session 课程，时间
91.female 女性 92.station 车站 93.kitchen 厨房 94.club 俱乐部 95.American 美国人 96.March3 月
97.February2 月 98.New Zealand 新西兰文化 99.Cambridge 剑桥 100.media 媒体 101.Scottish 苏格兰人
102.weekend 周 末 103.traveling 旅 游 104.park 公 园 105.October10 月 106.record 记 录 ， 唱 片
107.professor 教 授 108.team 队 伍 109.seat 座 位 110.May5 月 111.August8 月 112.child 儿 童
113.September9 月 114.Tuesday 周二 115.Friday 周五 116.Thursday 周四 117.surname 姓 118.trousers
裤子 119.subjects 主题 120.drinking 饮水 121.mail 邮件 122.male 男性 123.safety 安全 124.form 表格
125.ability 能力 126.evening 晚间 127.certificate 证书 128.further 进一步 129.shoes 鞋 130.tutorials
补课 131.April4 月 132.July7 月 133.June6 月 134.Saturday 周六 135.London 伦敦 136.entrance 入口
137.children 儿童 138.confidence 自信 139.zoo 动物园 140.standard 标准 141.exam 考试 142.case 案
例143.different 不同的144.requirement 要求145.dollars 美金146.bank 银行147.theory 理论148.visa
签证 149.assignment 作业 150.farm 农场 151.board 木板，董事会 152.painting 绘画 153.size 大小
154.railway 铁路 155.skill 技能 156.waste 浪费 157.price 价格 158.pollution 污染 159.hospital 医院
160.farming 农业 161.buildings 建筑物 162.contact 接触 163.dinner 晚餐 164.traffic 交通 165.date 日
期 166.bathroom 卫生间 167.video 录像 168.plus 加 169.results 结果 170.general 普通的 statistics 统
计学 171.effect 效果 172.wheel 方向盘，车轮 173.discount 打折 174.care 关注 175.practical 实际的音
机 176.accommodation 住宿 177.least 至少 178.mature 成熟的 179.purse 钱包 180.flexible 灵活的
181.store 商场 182.tour 旅游 183.view 风景，视线 184.handbook 手册 185.smoking 吸烟 186.individual
个 人 的 187.technical 科 技 的 188.colleges 学 院 189.variety 种 类 190.plants 植 物 191.top 顶 尖
192.Chinese 中文 193.thought 想法 194.major 专业 195.marks 分数 196.health 健康 197.sleep 睡觉
198.garden 花园 199.rent 房租 200.lock 锁`;

// Phonetic dictionary for common IELTS words
const phoneticMap = {
  'copy': '/ˈkɒpi/',
  'clock': '/klɒk/',
  'letter': '/ˈletə(r)/',
  'ticket': '/ˈtɪkɪt/',
  'transportation': '/ˌtrænspɔːˈteɪʃn/',
  'goals': '/ɡəʊlz/',
  'energy': '/ˈenədʒi/',
  'experience': '/ɪkˈspɪəriəns/',
  'January': '/ˈdʒænjuəri/',
  'second': '/ˈsekənd/',
  'America': '/əˈmerɪkə/',
  'Britain': '/ˈbrɪtn/',
  'London': '/ˈlʌndən/',
  'England': '/ˈɪŋɡlənd/',
  'Scotland': '/ˈskɒtlənd/',
  'Queensland': '/ˈkwiːnzlənd/',
  'Sydney': '/ˈsɪdni/',
  'Adelaide': '/ˈædəleɪd/',
  'Melbourne': '/ˈmelbən/',
  'Perth': '/pɜːθ/',
  'fire': '/ˈfaɪə(r)/',
  'college': '/ˈkɒlɪdʒ/',
  'teams': '/tiːmz/',
  'membership': '/ˈmembəʃɪp/',
  'difficulties': '/ˈdɪfɪkəltiz/',
  'beach': '/biːtʃ/',
  'underground': '/ˌʌndəˈɡraʊnd/',
  'spending': '/ˈspendɪŋ/',
  'site': '/saɪt/',
  'recreation': '/ˌrekriˈeɪʃn/',
  'property': '/ˈprɒpəti/',
  'learn': '/lɜːn/',
  'computers': '/kəmˈpjuːtəz/',
  'plant': '/plɑːnt/',
  'table': '/ˈteɪbl/',
  'support': '/səˈpɔːt/',
  'choice': '/tʃɔɪs/',
  'glass': '/ɡlɑːs/',
  'survey': '/ˈsɜːveɪ/',
  'passport': '/ˈpɑːspɔːt/',
  'range': '/reɪndʒ/',
  'service': '/ˈsɜːvɪs/',
  'exams': '/ɪɡˈzæmz/',
  'failure': '/ˈfeɪljə(r)/',
  'demonstration': '/ˌdemənˈstreɪʃn/',
  'festival': '/ˈfestɪvl/',
  'Belfast': '/ˈbelfɑːst/',
  'Ireland': '/ˈaɪələnd/',
  'Dublin': '/ˈdʌblɪn/',
  'Australia': '/ɒˈstreɪliə/',
  'narrator': '/nəˈreɪtə(r)/',
  'costs': '/kɒsts/',
  'background': '/ˈbækɡraʊnd/',
  'avenue': '/ˈævənjuː/',
  'senior': '/ˈsiːniə(r)/',
  'deposit': '/dɪˈpɒzɪt/',
  'extra': '/ˈekstrə/',
  'tape': '/teɪp/',
  'title': '/ˈtaɪtl/',
  'culture': '/ˈkʌltʃə(r)/',
  'dark': '/dɑːk/',
  'regular': '/ˈreɡjələ(r)/',
  'project': '/ˈprɒdʒekt/',
  'December': '/dɪˈsembə(r)/',
  'November': '/nəʊˈvembə(r)/',
  'beginning': '/bɪˈɡɪnɪŋ/',
  'purpose': '/ˈpɜːpəs/',
  'interest': '/ˈɪntrəst/',
  'decoration': '/ˌdekəˈreɪʃn/',
  'migration': '/maɪˈɡreɪʃn/',
  'party': '/ˈpɑːti/',
  'relationship': '/rɪˈleɪʃnʃɪp/',
  'environmental': '/ɪnˌvaɪrənˈmentl/',
  'disease': '/dɪˈziːz/',
  'Monday': '/ˈmʌndeɪ/',
  'Wednesday': '/ˈwenzdeɪ/',
  'century': '/ˈsentʃəri/',
  'equipment': '/ɪˈkwɪpmənt/',
  'methods': '/ˈmeθədz/',
  'location': '/ləʊˈkeɪʃn/',
  'transport': '/ˈtrænspɔːt/',
  'campus': '/ˈkæmpəs/',
  'ideas': '/aɪˈdɪəz/',
  'world': '/wɜːld/',
  'coffee': '/ˈkɒfi/',
  'third': '/θɜːd/',
  'fourth': '/fɔːθ/',
  'cause': '/kɔːz/',
  'social': '/ˈsəʊʃl/',
  'session': '/ˈseʃn/',
  'female': '/ˈfiːmeɪl/',
  'station': '/ˈsteɪʃn/',
  'kitchen': '/ˈkɪtʃɪn/',
  'club': '/klʌb/',
  'American': '/əˈmerɪkən/',
  'March': '/mɑːtʃ/',
  'February': '/ˈfebruəri/',
  'New Zealand': '/njuː ˈziːlənd/',
  'Cambridge': '/ˈkeɪmbrɪdʒ/',
  'media': '/ˈmiːdiə/',
  'Scottish': '/ˈskɒtɪʃ/',
  'weekend': '/ˌwiːkˈend/',
  'traveling': '/ˈtrævəlɪŋ/',
  'park': '/pɑːk/',
  'October': '/ɒkˈtəʊbə(r)/',
  'record': '/ˈrekɔːd/',
  'professor': '/prəˈfesə(r)/',
  'team': '/tiːm/',
  'seat': '/siːt/',
  'May': '/meɪ/',
  'August': '/ˈɔːɡəst/',
  'child': '/tʃaɪld/',
  'September': '/sepˈtembə(r)/',
  'Tuesday': '/ˈtjuːzdeɪ/',
  'Friday': '/ˈfraɪdeɪ/',
  'Thursday': '/ˈθɜːzdeɪ/',
  'surname': '/ˈsɜːneɪm/',
  'trousers': '/ˈtraʊzəz/',
  'subjects': '/ˈsʌbdʒɪkts/',
  'drinking': '/ˈdrɪŋkɪŋ/',
  'mail': '/meɪl/',
  'male': '/meɪl/',
  'safety': '/ˈseɪfti/',
  'form': '/fɔːm/',
  'ability': '/əˈbɪləti/',
  'evening': '/ˈiːvnɪŋ/',
  'certificate': '/səˈtɪfɪkət/',
  'further': '/ˈfɜːðə(r)/',
  'shoes': '/ʃuːz/',
  'tutorials': '/tjuːˈtɔːriəlz/',
  'April': '/ˈeɪprəl/',
  'July': '/dʒuˈlaɪ/',
  'June': '/dʒuːn/',
  'Saturday': '/ˈsætədeɪ/',
  'entrance': '/ˈentrəns/',
  'children': '/ˈtʃɪldrən/',
  'confidence': '/ˈkɒnfɪdəns/',
  'zoo': '/zuː/',
  'standard': '/ˈstændəd/',
  'exam': '/ɪɡˈzæm/',
  'case': '/keɪs/',
  'different': '/ˈdɪfrənt/',
  'requirement': '/rɪˈkwaɪəmənt/',
  'dollars': '/ˈdɒləz/',
  'bank': '/bæŋk/',
  'theory': '/ˈθɪəri/',
  'visa': '/ˈviːzə/',
  'assignment': '/əˈsaɪnmənt/',
  'farm': '/fɑːm/',
  'board': '/bɔːd/',
  'painting': '/ˈpeɪntɪŋ/',
  'size': '/saɪz/',
  'railway': '/ˈreɪlweɪ/',
  'skill': '/skɪl/',
  'waste': '/weɪst/',
  'price': '/praɪs/',
  'pollution': '/pəˈluːʃn/',
  'hospital': '/ˈhɒspɪtl/',
  'farming': '/ˈfɑːmɪŋ/',
  'buildings': '/ˈbɪldɪŋz/',
  'contact': '/ˈkɒntækt/',
  'dinner': '/ˈdɪnə(r)/',
  'traffic': '/ˈtræfɪk/',
  'date': '/deɪt/',
  'bathroom': '/ˈbɑːθruːm/',
  'video': '/ˈvɪdiəʊ/',
  'plus': '/plʌs/',
  'results': '/rɪˈzʌlts/',
  'general': '/ˈdʒenrəl/',
  'statistics': '/stəˈtɪstɪks/',
  'effect': '/ɪˈfekt/',
  'wheel': '/wiːl/',
  'discount': '/ˈdɪskaʊnt/',
  'care': '/keə(r)/',
  'practical': '/ˈpræktɪkl/',
  'accommodation': '/əˌkɒməˈdeɪʃn/',
  'least': '/liːst/',
  'mature': '/məˈtʃʊə(r)/',
  'purse': '/pɜːs/',
  'flexible': '/ˈfleksəbl/',
  'store': '/stɔː(r)/',
  'tour': '/tʊə(r)/',
  'view': '/vjuː/',
  'handbook': '/ˈhændbʊk/',
  'smoking': '/ˈsməʊkɪŋ/',
  'individual': '/ˌɪndɪˈvɪdʒuəl/',
  'technical': '/ˈteknɪkl/',
  'colleges': '/ˈkɒlɪdʒɪz/',
  'variety': '/vəˈraɪəti/',
  'plants': '/plɑːnts/',
  'top': '/tɒp/',
  'Chinese': '/ˌtʃaɪˈniːz/',
  'thought': '/θɔːt/',
  'major': '/ˈmeɪdʒə(r)/',
  'marks': '/mɑːks/',
  'health': '/helθ/',
  'sleep': '/sliːp/',
  'garden': '/ˈɡɑːdn/',
  'rent': '/rent/',
  'lock': '/lɒk/'
};

// Example sentences templates
const exampleTemplates = {
  'copy': { en: 'Please make a copy of this document for the meeting.', zh: '请为会议复印一份这个文件。' },
  'clock': { en: 'The lecture starts at three o\'clock in the afternoon.', zh: '讲座在下午三点开始。' },
  'letter': { en: 'I received a letter from the university about my application.', zh: '我收到了大学关于我申请的信件。' },
  'ticket': { en: 'You need to book your train ticket in advance.', zh: '你需要提前预订火车票。' },
  'transportation': { en: 'Public transportation is very convenient in this city.', zh: '这个城市的公共交通非常便利。' },
  'goals': { en: 'Setting clear academic goals helps students achieve better results.', zh: '设定明确的学术目标有助于学生取得更好的成绩。' },
  'energy': { en: 'Renewable energy is becoming more important for our environment.', zh: '可再生能源对我们的环境变得越来越重要。' },
  'experience': { en: 'This internship will give you valuable work experience.', zh: '这次实习将给你宝贵的工作经验。' },
  'January': { en: 'The winter semester usually begins in January.', zh: '冬季学期通常在一月开始。' },
  'second': { en: 'This is the second time I have visited this museum.', zh: '这是我第二次参观这个博物馆。' },
  'America': { en: 'Many international students choose to study in America.', zh: '许多国际学生选择在美国学习。' },
  'Britain': { en: 'Britain has a rich history and cultural heritage.', zh: '英国拥有丰富的历史和文化遗产。' },
  'London': { en: 'London is one of the most popular destinations for tourists.', zh: '伦敦是最受游客欢迎的目的地之一。' },
  'England': { en: 'England has many prestigious universities and colleges.', zh: '英格兰有许多著名的大学和学院。' },
  'Scotland': { en: 'Scotland is famous for its beautiful landscapes and historic castles.', zh: '苏格兰以其美丽的风景和历史悠久的城堡而闻名。' },
  'Queensland': { en: 'Queensland offers excellent opportunities for studying marine biology.', zh: '昆士兰为学习海洋生物学提供了绝佳的机会。' },
  'Sydney': { en: 'Sydney is the largest city in Australia.', zh: '悉尼是澳大利亚最大的城市。' },
  'Adelaide': { en: 'Adelaide is known for its festivals and quality education.', zh: '阿德莱德以其节日和优质教育而闻名。' },
  'Melbourne': { en: 'Melbourne has a diverse culture and vibrant arts scene.', zh: '墨尔本拥有多元文化和充满活力的艺术氛围。' },
  'Perth': { en: 'Perth is located on the west coast of Australia.', zh: '珀斯位于澳大利亚西海岸。' },
  'fire': { en: 'The fire alarm went off during the examination.', zh: '考试期间火灾警报响了。' },
  'college': { en: 'She is studying business management at a local college.', zh: '她在当地一所学院学习商业管理。' },
  'teams': { en: 'Students are divided into teams for the group project.', zh: '学生们被分成小组完成小组项目。' },
  'membership': { en: 'The gym membership includes access to all facilities.', zh: '健身房会员资格包括使用所有设施。' },
  'difficulties': { en: 'International students may face difficulties adjusting to a new culture.', zh: '国际学生可能在适应新文化方面面临困难。' },
  'beach': { en: 'The beach is a popular place for relaxation on weekends.', zh: '海滩是周末放松的热门场所。' },
  'underground': { en: 'The underground train system is the fastest way to travel.', zh: '地铁系统是最快的出行方式。' },
  'spending': { en: 'Students should plan their spending carefully to manage their budget.', zh: '学生应该仔细规划支出以管理预算。' },
  'site': { en: 'The construction site is located near the university campus.', zh: '建筑工地位于大学校园附近。' },
  'recreation': { en: 'The recreation center offers various sports and activities.', zh: '娱乐中心提供各种运动和活动。' },
  'property': { en: 'Renting property near campus can be quite expensive.', zh: '在校园附近租房可能相当昂贵。' },
  'learn': { en: 'Students need to learn effective time management skills.', zh: '学生需要学习有效的时间管理技能。' },
  'computers': { en: 'All students have access to computers in the library.', zh: '所有学生都可以使用图书馆的电脑。' },
  'plant': { en: 'The botany course includes studying different plant species.', zh: '植物学课程包括研究不同的植物物种。' },
  'table': { en: 'Please reserve a table at the study room for our group.', zh: '请为我们小组在自习室预订一张桌子。' },
  'support': { en: 'The university provides excellent support services for students.', zh: '大学为学生提供优秀的支持服务。' },
  'choice': { en: 'Students have a wide choice of elective courses.', zh: '学生有广泛的选修课程可供选择。' },
  'glass': { en: 'The library building features beautiful glass architecture.', zh: '图书馆大楼具有美丽的玻璃建筑特色。' },
  'survey': { en: 'We conducted a survey to understand student satisfaction.', zh: '我们进行了一项调查以了解学生满意度。' },
  'passport': { en: 'Don\'t forget to bring your passport for international travel.', zh: '国际旅行时别忘了带上护照。' },
  'range': { en: 'The library offers a wide range of academic resources.', zh: '图书馆提供广泛的学术资源。' },
  'service': { en: 'The customer service at the bookstore is very helpful.', zh: '书店的客户服务非常有帮助。' },
  'exams': { en: 'Final exams will be held in the examination hall.', zh: '期末考试将在考场举行。' },
  'failure': { en: 'Failure is an important part of the learning process.', zh: '失败是学习过程的重要组成部分。' },
  'demonstration': { en: 'The professor gave a practical demonstration in the laboratory.', zh: '教授在实验室进行了实际演示。' },
  'festival': { en: 'The university hosts an international festival every year.', zh: '大学每年举办一次国际节日。' },
  'Belfast': { en: 'Belfast is the capital city of Northern Ireland.', zh: '贝尔法斯特是北爱尔兰的首府。' },
  'Ireland': { en: 'Ireland is known for its friendly people and green landscapes.', zh: '爱尔兰以其友好的人民和绿色的风景而闻名。' },
  'Dublin': { en: 'Dublin has several world-class universities and research centers.', zh: '都柏林有几所世界级的大学和研究中心。' },
  'Australia': { en: 'Australia attracts thousands of international students each year.', zh: '澳大利亚每年吸引数千名国际学生。' },
  'narrator': { en: 'The narrator provides important context throughout the audio recording.', zh: '叙述者在整个录音中提供重要的背景信息。' },
  'costs': { en: 'Living costs in major cities are generally higher than in small towns.', zh: '大城市的生活成本通常高于小城镇。' },
  'background': { en: 'Students from different cultural backgrounds enrich classroom discussions.', zh: '来自不同文化背景的学生丰富了课堂讨论。' },
  'avenue': { en: 'The main campus is located on Park Avenue.', zh: '主校区位于公园大道。' },
  'senior': { en: 'Senior students often mentor first-year undergraduates.', zh: '大四学生经常指导一年级本科生。' },
  'deposit': { en: 'You need to pay a deposit before moving into the apartment.', zh: '在搬进公寓之前你需要支付押金。' },
  'extra': { en: 'Students can attend extra tutorials to improve their grades.', zh: '学生可以参加额外的辅导课来提高成绩。' },
  'tape': { en: 'Listen to the tape carefully and answer the questions.', zh: '仔细听录音带并回答问题。' },
  'title': { en: 'Choose an appropriate title for your research paper.', zh: '为你的研究论文选择一个合适的标题。' },
  'culture': { en: 'Understanding local culture helps international students adapt better.', zh: '了解当地文化有助于国际学生更好地适应。' },
  'dark': { en: 'The library stays open until dark during exam period.', zh: '考试期间图书馆一直开放到天黑。' },
  'regular': { en: 'Maintaining regular study habits is essential for academic success.', zh: '保持规律的学习习惯对学术成功至关重要。' },
  'project': { en: 'The final project accounts for forty percent of the course grade.', zh: '期末项目占课程成绩的百分之四十。' },
  'December': { en: 'Most universities have winter break in December.', zh: '大多数大学在十二月有寒假。' },
  'November': { en: 'Assignment submissions are due in November.', zh: '作业提交截止日期在十一月。' },
  'beginning': { en: 'The beginning of the semester is always very busy.', zh: '学期开始时总是非常忙碌。' },
  'purpose': { en: 'The main purpose of this course is to develop critical thinking.', zh: '这门课程的主要目的是培养批判性思维。' },
  'interest': { en: 'Developing an interest in reading improves language skills.', zh: '培养阅读兴趣可以提高语言技能。' },
  'decoration': { en: 'The decoration of the conference hall looks professional.', zh: '会议厅的装饰看起来很专业。' },
  'migration': { en: 'The course covers patterns of human migration throughout history.', zh: '该课程涵盖了整个历史中人类迁徙的模式。' },
  'party': { en: 'The student union is organizing a welcome party.', zh: '学生会正在组织欢迎晚会。' },
  'relationship': { en: 'Building good relationships with classmates is important.', zh: '与同学建立良好的关系很重要。' },
  'environmental': { en: 'Environmental science is becoming an increasingly popular major.', zh: '环境科学正在成为越来越受欢迎的专业。' },
  'disease': { en: 'Medical researchers are working to find cures for various diseases.', zh: '医学研究人员正在努力寻找各种疾病的治疗方法。' },
  'Monday': { en: 'We have a lecture every Monday morning at nine.', zh: '我们每周一早上九点有一节课。' },
  'Wednesday': { en: 'The seminar is scheduled for Wednesday afternoon.', zh: '研讨会安排在周三下午。' },
  'century': { en: 'This building was constructed in the nineteenth century.', zh: '这座建筑建于十九世纪。' },
  'equipment': { en: 'The laboratory has modern equipment for scientific research.', zh: '实验室拥有现代化的科学研究设备。' },
  'methods': { en: 'Different teaching methods work better for different students.', zh: '不同的教学方法对不同的学生更有效。' },
  'location': { en: 'The location of the university is convenient for public transport.', zh: '大学的地理位置便于公共交通。' },
  'transport': { en: 'Students can get discounts on public transport.', zh: '学生可以获得公共交通折扣。' },
  'campus': { en: 'The campus has excellent facilities for sports and recreation.', zh: '校园拥有出色的体育和娱乐设施。' },
  'ideas': { en: 'Students are encouraged to share their ideas in class.', zh: '鼓励学生在课堂上分享他们的观点。' },
  'world': { en: 'The university attracts students from all over the world.', zh: '这所大学吸引来自世界各地的学生。' },
  'coffee': { en: 'Many students study in the coffee shop on campus.', zh: '许多学生在校园的咖啡店学习。' },
  'third': { en: 'The meeting room is on the third floor of the building.', zh: '会议室在大楼的三楼。' },
  'fourth': { en: 'This is my fourth year studying at this university.', zh: '这是我在这所大学学习的第四年。' },
  'cause': { en: 'Understanding the cause of the problem is the first step.', zh: '了解问题的起因是第一步。' },
  'social': { en: 'Social activities help students make new friends.', zh: '社交活动帮助学生结交新朋友。' },
  'session': { en: 'Each training session lasts approximately two hours.', zh: '每节培训课程大约持续两小时。' },
  'female': { en: 'Female students make up sixty percent of the class.', zh: '女学生占班级的百分之六十。' },
  'station': { en: 'The train station is just five minutes from campus.', zh: '火车站离校园只有五分钟路程。' },
  'kitchen': { en: 'The shared kitchen in the dormitory is well equipped.', zh: '宿舍的共用厨房设备齐全。' },
  'club': { en: 'Joining a club is a great way to meet people.', zh: '加入俱乐部是认识人的好方法。' },
  'American': { en: 'American universities are popular among international students.', zh: '美国大学在国际学生中很受欢迎。' },
  'March': { en: 'The spring semester usually ends in March.', zh: '春季学期通常在三月结束。' },
  'February': { en: 'Registration for next semester opens in February.', zh: '下学期的注册在二月开放。' },
  'New Zealand': { en: 'New Zealand offers high-quality education in a beautiful environment.', zh: '新西兰在优美的环境中提供高质量的教育。' },
  'Cambridge': { en: 'Cambridge is one of the oldest and most prestigious universities.', zh: '剑桥是最古老和最负盛名的大学之一。' },
  'media': { en: 'Social media has changed the way students communicate.', zh: '社交媒体改变了学生的交流方式。' },
  'Scottish': { en: 'Scottish universities are known for their excellent research programs.', zh: '苏格兰大学以其卓越的研究项目而闻名。' },
  'weekend': { en: 'Most students relax and socialize on the weekend.', zh: '大多数学生在周末放松和社交。' },
  'traveling': { en: 'Traveling abroad is a great way to learn about different cultures.', zh: '出国旅行是了解不同文化的好方法。' },
  'park': { en: 'The city park is a popular spot for outdoor activities.', zh: '城市公园是户外活动的热门地点。' },
  'October': { en: 'The autumn semester usually starts in October.', zh: '秋季学期通常在十月开始。' },
  'record': { en: 'The university keeps a record of all student achievements.', zh: '大学保存所有学生成就的记录。' },
  'professor': { en: 'The professor has over twenty years of teaching experience.', zh: '这位教授有超过二十年的教学经验。' },
  'team': { en: 'Each team must complete the project by the deadline.', zh: '每个团队必须在截止日期前完成项目。' },
  'seat': { en: 'Please find a seat before the lecture begins.', zh: '请在讲座开始前找个座位。' },
  'May': { en: 'Final exams are typically held in May.', zh: '期末考试通常在五月举行。' },
  'August': { en: 'The summer program runs from June to August.', zh: '暑期课程从六月持续到八月。' },
  'child': { en: 'The child development program focuses on early education.', zh: '儿童发展项目专注于早期教育。' },
  'September': { en: 'The academic year begins in September.', zh: '学年从九月开始。' },
  'Tuesday': { en: 'The weekly tutorial is held on Tuesday afternoon.', zh: '每周的辅导课在周二下午举行。' },
  'Friday': { en: 'Friday is the last day of classes for the week.', zh: '周五是一周课程的最后一天。' },
  'Thursday': { en: 'The department meeting is scheduled for Thursday morning.', zh: '系会议安排在周四上午。' },
  'surname': { en: 'Please write your surname in capital letters on the form.', zh: '请在表格上用大写字母写下你的姓氏。' },
  'trousers': { en: 'Smart trousers are required for the formal presentation.', zh: '正式演讲需要穿着得体的裤子。' },
  'subjects': { en: 'Students must choose five subjects for this semester.', zh: '学生本学期必须选择五门科目。' },
  'drinking': { en: 'Drinking water fountains are located throughout the campus.', zh: '饮水机遍布整个校园。' },
  'mail': { en: 'Check your mail regularly for important announcements.', zh: '定期查看邮件以获取重要通知。' },
  'male': { en: 'Male students represent forty percent of the enrollment.', zh: '男学生占入学人数的百分之四十。' },
  'safety': { en: 'Campus safety is a top priority for the university.', zh: '校园安全是大学的首要任务。' },
  'form': { en: 'Please complete the application form before the deadline.', zh: '请在截止日期前填写申请表。' },
  'ability': { en: 'The course helps develop critical thinking ability.', zh: '该课程有助于培养批判性思维能力。' },
  'evening': { en: 'Evening classes are available for part-time students.', zh: '兼职学生可以上晚间课程。' },
  'certificate': { en: 'Students will receive a certificate upon course completion.', zh: '学生将在完成课程后获得证书。' },
  'further': { en: 'Further information is available on the university website.', zh: '更多信息可在大学网站上找到。' },
  'shoes': { en: 'Remember to bring appropriate shoes for the field trip.', zh: '记得为实地考察带合适的鞋子。' },
  'tutorials': { en: 'Weekly tutorials help reinforce lecture material.', zh: '每周的辅导课帮助巩固讲座内容。' },
  'April': { en: 'The spring break typically falls in April.', zh: '春假通常在四月。' },
  'July': { en: 'The summer semester continues through July.', zh: '夏季学期持续到七月。' },
  'June': { en: 'Graduation ceremonies take place in June.', zh: '毕业典礼在六月举行。' },
  'Saturday': { en: 'The library has reduced hours on Saturday.', zh: '图书馆周六缩短开放时间。' },
  'entrance': { en: 'The main entrance to the campus is on Green Street.', zh: '校园的主入口在格林街。' },
  'children': { en: 'The children\'s education program focuses on language development.', zh: '儿童教育项目专注于语言发展。' },
  'confidence': { en: 'Public speaking helps build confidence in students.', zh: '公开演讲有助于建立学生的自信心。' },
  'zoo': { en: 'The biology class will visit the zoo next week.', zh: '生物课下周将参观动物园。' },
  'standard': { en: 'The university maintains high academic standards.', zh: '大学保持高学术标准。' },
  'exam': { en: 'The final exam will cover all course material.', zh: '期末考试将涵盖所有课程内容。' },
  'case': { en: 'Each case study requires detailed analysis and discussion.', zh: '每个案例研究都需要详细的分析和讨论。' },
  'different': { en: 'Different students have different learning styles.', zh: '不同的学生有不同的学习风格。' },
  'requirement': { en: 'Meeting the attendance requirement is essential for passing.', zh: '满足出勤要求对于通过考试至关重要。' },
  'dollars': { en: 'The textbook costs fifty dollars at the bookstore.', zh: '这本教科书在书店售价五十美元。' },
  'bank': { en: 'There is a bank branch located near the student union.', zh: '学生会附近有一家银行分行。' },
  'theory': { en: 'The course covers both theory and practical application.', zh: '该课程涵盖理论和实际应用。' },
  'visa': { en: 'International students need a valid student visa.', zh: '国际学生需要有效的学生签证。' },
  'assignment': { en: 'The assignment is due next Monday at midnight.', zh: '作业的截止日期是下周一午夜。' },
  'farm': { en: 'The agricultural science students visited a local farm.', zh: '农业科学专业的学生参观了当地农场。' },
  'board': { en: 'The notice board displays important announcements.', zh: '公告栏展示重要公告。' },
  'painting': { en: 'The art gallery features a collection of modern painting.', zh: '艺术画廊展示现代绘画收藏。' },
  'size': { en: 'Class size is limited to twenty students per session.', zh: '每节课的班级规模限制在二十名学生。' },
  'railway': { en: 'The railway station connects the city to major destinations.', zh: '火车站将城市连接到主要目的地。' },
  'skill': { en: 'Communication skill is essential in today\'s workplace.', zh: '沟通技能在当今职场中至关重要。' },
  'waste': { en: 'Recycling helps reduce waste on campus.', zh: '回收有助于减少校园浪费。' },
  'price': { en: 'The price of accommodation varies by location.', zh: '住宿价格因地点而异。' },
  'pollution': { en: 'Air pollution is a major environmental concern.', zh: '空气污染是一个主要的环境问题。' },
  'hospital': { en: 'The university hospital provides health services to students.', zh: '大学医院为学生提供医疗服务。' },
  'farming': { en: 'Sustainable farming practices are taught in the agriculture course.', zh: '农业课程教授可持续农业实践。' },
  'buildings': { en: 'The campus buildings are equipped with modern facilities.', zh: '校园建筑配备现代化设施。' },
  'contact': { en: 'Please contact the admissions office for more information.', zh: '请联系招生办公室了解更多信息。' },
  'dinner': { en: 'The welcome dinner will be held in the main hall.', zh: '欢迎晚宴将在主厅举行。' },
  'traffic': { en: 'Heavy traffic can make commuting difficult during rush hour.', zh: '高峰时段的交通拥堵可能使通勤变得困难。' },
  'date': { en: 'Please check the date of the examination on the notice board.', zh: '请在公告栏上查看考试日期。' },
  'bathroom': { en: 'Each apartment has a private bathroom.', zh: '每个公寓都有私人浴室。' },
  'video': { en: 'The lecture video is available online for review.', zh: '讲座视频可在线查看复习。' },
  'plus': { en: 'The course fee is two hundred pounds plus registration costs.', zh: '课程费用是二百英镑加上注册费用。' },
  'results': { en: 'Exam results will be posted online next week.', zh: '考试结果将在下周在线发布。' },
  'general': { en: 'The general consensus is that the course is very useful.', zh: '普遍共识是这门课程非常有用。' },
  'statistics': { en: 'Statistics is a required course for economics majors.', zh: '统计学是经济学专业的必修课程。' },
  'effect': { en: 'The new policy had a positive effect on student satisfaction.', zh: '新政策对学生满意度产生了积极影响。' },
  'wheel': { en: 'Bicycle parking areas with wheel racks are available.', zh: '提供带车轮架的自行车停车区。' },
  'discount': { en: 'Students receive a twenty percent discount at local shops.', zh: '学生在当地商店享受八折优惠。' },
  'care': { en: 'The university takes care of student welfare and wellbeing.', zh: '大学关注学生的福利和福祉。' },
  'practical': { en: 'The practical component of the course involves laboratory work.', zh: '课程的实践部分涉及实验室工作。' },
  'accommodation': { en: 'Student accommodation is available both on and off campus.', zh: '校内和校外都有学生住宿。' },
  'least': { en: 'You should spend at least two hours studying each day.', zh: '你每天至少应该花两个小时学习。' },
  'mature': { en: 'Mature students bring valuable life experience to the classroom.', zh: '成熟学生为课堂带来宝贵的生活经验。' },
  'purse': { en: 'Keep your purse secure in crowded areas.', zh: '在拥挤的地方保管好你的钱包。' },
  'flexible': { en: 'The program offers flexible study options for working students.', zh: '该项目为在职学生提供灵活的学习选择。' },
  'store': { en: 'The campus store sells textbooks and stationery.', zh: '校园商店出售教科书和文具。' },
  'tour': { en: 'Campus tour guides show prospective students around the facilities.', zh: '校园导游带领未来的学生参观设施。' },
  'view': { en: 'The library offers a spectacular view of the city.', zh: '图书馆可以看到城市的壮观景色。' },
  'handbook': { en: 'The student handbook contains important policies and procedures.', zh: '学生手册包含重要的政策和程序。' },
  'smoking': { en: 'Smoking is not permitted inside university buildings.', zh: '大学建筑内禁止吸烟。' },
  'individual': { en: 'Each individual student has unique learning needs.', zh: '每个学生都有独特的学习需求。' },
  'technical': { en: 'Technical support is available for computer problems.', zh: '技术支持可用于解决电脑问题。' },
  'colleges': { en: 'The university consists of several different colleges.', zh: '该大学由几个不同的学院组成。' },
  'variety': { en: 'The cafeteria offers a wide variety of food choices.', zh: '自助餐厅提供各种各样的食物选择。' },
  'plants': { en: 'The biology lab has various plants for study purposes.', zh: '生物实验室有各种植物供学习使用。' },
  'top': { en: 'This university is ranked among the top institutions globally.', zh: '这所大学位列全球顶尖机构之列。' },
  'Chinese': { en: 'Chinese language courses are very popular among international students.', zh: '汉语课程在国际学生中非常受欢迎。' },
  'thought': { en: 'Critical thought is encouraged in all academic discussions.', zh: '在所有学术讨论中都鼓励批判性思考。' },
  'major': { en: 'Students declare their major at the end of second year.', zh: '学生在二年级结束时宣布他们的专业。' },
  'marks': { en: 'Students receive marks based on their performance in assignments.', zh: '学生根据作业表现获得分数。' },
  'health': { en: 'The health center provides free medical services to students.', zh: '健康中心为学生提供免费医疗服务。' },
  'sleep': { en: 'Getting enough sleep is important for academic performance.', zh: '充足的睡眠对学习成绩很重要。' },
  'garden': { en: 'The botanical garden is a peaceful place for studying.', zh: '植物园是学习的宁静之地。' },
  'rent': { en: 'Monthly rent for student apartments starts at five hundred pounds.', zh: '学生公寓的月租金从五百英镑起。' },
  'lock': { en: 'Remember to lock your room when you leave.', zh: '离开时记得锁好你的房间。' }
};

// Parse the raw text
function parseWords(text) {
  const words = [];
  // Match pattern: number.word translation
  const regex = /(\d+)\.([a-zA-Z\s]+)\s+([^\d]+?)(?=\s+\d+\.|$)/g;
  let match;

  while ((match = regex.exec(text)) !== null) {
    const id = parseInt(match[1]);
    const word = match[2].trim();
    const translation = match[3].trim().replace(/\s+/g, '');

    if (id <= 200) {
      const day = id <= 50 ? 1 : 2;
      const phonetic = phoneticMap[word] || `/${word}/`;
      const example = exampleTemplates[word] || {
        en: `This is an example sentence with the word ${word}.`,
        zh: `这是一个包含单词${word}的例句。`
      };

      words.push({
        id,
        word,
        translation,
        phonetic,
        example,
        day
      });
    }
  }

  return words.sort((a, b) => a.id - b.id);
}

const words = parseWords(rawText);

console.log(`Parsed ${words.length} words`);
console.log('Writing to JSON file...');

fs.writeFileSync(
  '/home/user/ielts-vocabulary-app/data/words.json',
  JSON.stringify(words, null, 2),
  'utf-8'
);

console.log('Done! File saved to data/words.json');
